services:
  nginx:
    container_name: nginx
    hostname: localhost
    image: nginx
    build:
      context: ./.docker/nginx
      dockerfile: Dockerfile   
    volumes: 
      - ./client/dist:/usr/share/nginx/html 
      - ./.docker/nginx/nginx.conf:/etc/nginx/nginx.conf 
      - ./.docker/nginx/proxy.conf:/etc/nginx/proxy.conf 
     # - /full_path/volumes/nginx/data:/usr/share/nginx/html
    ports:
      - 8080:80
      - 8081:443
    links:
      - server 
  server:
    container_name: server 
    image: ${DOCKER_REGISTRY-}server
    build:
      context: .
      dockerfile: Server/Dockerfile  
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=5000
      - ASPNETCORE_HTTPS_PORTS=5001
    working_dir: /app
    ports: 
      - "5001:5001"  
      - "5000:5000"  
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro 
    
    
    